- name: Create the ELB only listening over port 80
  ec2_elb_lb:
    name: "{{ ELB_NAME }}"
    state: present
    region: us-east-1
    zones:
      - us-east-1a
      - us-east-1b
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
  register: elb

- name: Create EC2 instances
  ec2:
    key_name: capstone
    instance_type: t2.micro
    image: ami-0986c2ac728528ac2
    user_data: "{{ USERDATA }}"
    region: us-east-1
    group_id:
      - sg-0c93978b488c8e844
    wait: yes
    instance_tags:
      Name: Capstone Server
      application: "{{ application }}"
    exact_count: 2
    count_tag:
      application: "{{ application }}"
  register: ec2_instances

- name: Wait for servers to come online
  wait_for:
    host: "{{ item.public_ip }}"
    port: 80
  with_items: "{{ ec2_instances.tagged_instances }}"
  ignore_errors: True

- name: Add each EC2 instance to the ELB
  ec2_elb:
    state: present
    ec2_elbs: "{{ ELB_NAME }}"
    region: "{{ item.region }}"
    instance_id: "{{ item.id }}"
  with_items: "{{ ec2_instances.instances }}"
