version: "3.8"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    image: minorpatch/capstone-nginx
    restart: always
    ports:
      - "80:80"

  flask:
    build: ./flask
    container_name: flask
    image: minorpatch/capstone-flask
    restart: always
    environment:
      - APP_NAME="Docker App"
    expose:
      - 8080
    depends_on: nginx
