apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-${ROLE}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      role: ${ROLE}
  template:
    metadata:
      labels:
        app: nginx
        role: ${ROLE}
    spec:
      containers:
        - name: nginx
          image: minorpatch/capstone-nginx:${ROLE}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
