apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-blue
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      role: blue
  template:
    metadata:
      labels:
        app: nginx
        role: blue
    spec:
      containers:
        - name: nginx
          image: minorpatch/capstone-nginx:blue
          env:
            - name: APP_NAME
              value: BLUE APP
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
