apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-green
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
        role: green
    spec:
      containers:
        - name: nginx
          image: nginx:1.18.0-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
