# Create a health-check for host1.example.com and use it in record
- route53_health_check:
    state: present
    fqdn: www.capstone.io
    type: HTTP
    resource_path: /
    request_interval: 15
    failure_threshold: 2
  register: hc

- name: change route53
  route53:
    state: present
    zone: capstone.io
    record: www.capstone.io
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ elb.dns_name }}"
    wait: yes
    health_check: "{{ hc.health_check.id }}"
