- name: change route53
  route53:
    state: present
    zone: capstone.io
    record: www.capstone.io
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "13f098e2-9655-4c35-9cab-40b94664b161"
