- name: create health check
  route53_health_check:
    state: present
    fqdn: www.capstone.io
    type: HTTP
    resource_path: /index.html
    request_interval: 10
    failure_threshold: 2
  register: hc

- name: update route53
  route53:
    state: present
    zone: capstone.io
    record: www.capstone.io
    failover: SECONDARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ ELB_DNS_NAME }}"
    wait: yes
    health_check: "{{ hc.health_check.id }}"
