apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: linting
spec:
  resources:
    inputs:
      - name: git-source
        type: git
  params:
    - name: python-image
      type: string
      default: python:3.7-alpine
  steps:
    - name: linting
      image: $(params.python-image)
      workingDir: $(resources.inputs.git-source.path)
      script: |
        python -m pip install flake8
        python -m flake8 ./code
