apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: publish-images
spec:
  resources:
    inputs:
      - name: git-source
        type: git
      - name: nginx-image
        type: image
      - name: flask-image
        type: image
  steps:
    - name: publish-nginx-image
      image: docker:dind
      securityContext:
        privileged: true
      args:
        - push
        - $(resources.inputs.nginx-image.url)
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
    - name: publish-flask-image
      image: docker:dind
      securityContext:
        privileged: true
      args:
        - push
        - $(resources.inputs.flask-image.url)
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
