apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    role: ${ROLE}
    env: production
spec:
  type: LoadBalancer
  selector:
    app: nginx
    role: ${ROLE}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
