apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    role: blue
    env: production
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: nginx
    role: blue
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
