apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-cluster
  region: us-east-1

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 4
  iam:
    withAddonPolicies:
      albIngress: true
