apiVersion: v1
kind: Secret
metadata:
  name: docker-creds
  annotations:
    tekton.dev/docker-0: index.docker.io
type: kubernetes.io/basic-auth
stringData:
  username: $(DOCKER_USER)
  password: $(DOCKER_PASSWORD)
